### ISSUE TITLE
Add an option to make Chunk image a link

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/email-gen#1]

**Comment by streeetlamp** [comment]
@dstrogiy plz stop doing your actual job, install this theme locally again and let me know if this is still an issue. ty

**Comment by streeetlamp** [comment]
payment for your services below 

![giphy](https://cloud.githubusercontent.com/assets/1740634/18017819/655602f2-6ba1-11e6-9e70-93ab60516f7e.gif)
