### ISSUE TITLE
Design won't resize properly on mobile

### ISSUE THREAD

**Issue by mrndlng** [VCUarts/email-gen#3]
![screen shot 2016-08-18 at 4 01 14 pm](https://cloud.githubusercontent.com/assets/19610484/17788644/b646077a-655c-11e6-8707-97258225f339.png)
![screen shot 2016-08-18 at 4 01 37 pm](https://cloud.githubusercontent.com/assets/19610484/17788643/b6391470-655c-11e6-95ac-869ed2593a8a.png)

**Comment by streeetlamp** [comment]
@mrndlng i think this is fixed or at least better???

**Comment by streeetlamp** [comment]
def better
