### ISSUE TITLE
Make spacing even on left and right of hero image

### ISSUE THREAD

**Issue by mrndlng** [VCUarts/email-gen#7]
![screen shot 2016-08-18 at 4 57 49 pm](https://cloud.githubusercontent.com/assets/19610484/17790471/940ab464-6564-11e6-86e2-0cf7c8db8160.png)

**Comment by streeetlamp** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1740634/18014171/b2e442de-6b8f-11e6-93b9-90699ed3c270.gif)

closing since the commit did not...
